[tool.poetry]
name = ""
version = ""
description = ""
readme = "README.md"
authors = []
packages = [{ include = "" }]

[tool.poetry.dependencies]
python = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
